jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: release apk sign
      run: "echo \"\u7ED9apk\u589E\u52A0\u7B7E\u540D\"\ncp $GITHUB_WORKSPACE/.github/workflows/android.keystore\
        \ $GITHUB_WORKSPACE/app/android.keystore\nsed '$a\\RELEASE_STORE_FILE=./android.keystore'\
        \          $GITHUB_WORKSPACE/gradle.properties -i\n"
    - continue-on-error: true
      name: build with gradle
      run: "echo \"\u5F00\u59CB\u8FDB\u884Crelease\u6784\u5EFA\"\nchmod +x gradlew\n\
        ./gradlew app:assembleRelease\n"
    - continue-on-error: true
      if: always()
      name: upload apk
      uses: actions/upload-artifact@master
      with:
        name: xupdate_apk
        path: ${{ github.workspace }}/app/build/outputs/apk/release
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___package.yml
